apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pu2p
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-pu2p@sha256:cf357e27a4075522bc4ecfaba2462e1842d404aeb1a29457773eee4a41ed07dd
        name: my-nodejs
        resources: {}
status: {}
